// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Connect(arg1:string,arg2:models.ServerNode,arg3:number,arg4:number):Promise<models.ConnectResult>;

export function DeleteCredential(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetCredentials():Promise<Array<models.Credential>>;

export function GetServers():Promise<Array<models.ServerNode>>;

export function GetSettings():Promise<models.Settings>;

export function ListSessions():Promise<Array<models.SessionInfo>>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveCredential(arg1:models.Credential):Promise<models.Credential>;

export function SaveServer(arg1:models.ServerNode):Promise<models.ServerNode>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SelectImageFile():Promise<string>;

export function SelectKeyFile():Promise<string>;

export function SftpList(arg1:string,arg2:string):Promise<Array<models.SFTPEntry>>;

export function Write(arg1:string,arg2:string):Promise<void>;
