// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddCommandHistory(arg1:string,arg2:string):Promise<void>;

export function AddGroup(arg1:string):Promise<void>;

export function ChangeMasterPassword(arg1:string,arg2:string):Promise<void>;

export function ClearCommandHistory(arg1:string):Promise<void>;

export function Connect(arg1:string,arg2:models.ServerNode,arg3:number,arg4:number):Promise<models.ConnectResult>;

export function DeleteCredential(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DisableMasterPassword(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function EnableMasterPassword(arg1:string):Promise<void>;

export function ExportConfig(arg1:string):Promise<string>;

export function GetCredentials():Promise<Array<models.Credential>>;

export function GetGroups():Promise<Array<string>>;

export function GetSecurityStatus():Promise<models.SecurityStatus>;

export function GetServers():Promise<Array<models.ServerNode>>;

export function GetSettings():Promise<models.Settings>;

export function ImportConfig(arg1:string,arg2:boolean):Promise<models.ImportConfigResult>;

export function ListSessions():Promise<Array<models.SessionInfo>>;

export function ListTunnels():Promise<Array<models.TunnelInfo>>;

export function QueryCommandHistory(arg1:string,arg2:string,arg3:number):Promise<Array<models.CommandSuggestion>>;

export function ReadLocalFileBase64(arg1:string):Promise<string>;

export function Reconnect(arg1:string,arg2:number,arg3:number):Promise<models.ConnectResult>;

export function RemoveGroup(arg1:string):Promise<void>;

export function RemoveTunnel(arg1:string):Promise<void>;

export function RenameGroup(arg1:string,arg2:string):Promise<void>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartTunnel(arg1:string):Promise<void>;

export function SaveCredential(arg1:models.Credential):Promise<models.Credential>;

export function SaveServer(arg1:models.ServerNode):Promise<models.ServerNode>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SelectImageFile():Promise<string>;

export function SelectKeyFile():Promise<string>;

export function SelectLocalFile():Promise<string>;

export function SelectLocalFiles():Promise<Array<string>>;

export function SelectSavePath(arg1:string):Promise<string>;

export function SetSftpPathFromTerminal(arg1:string,arg2:string):Promise<void>;

export function SetSysInfoIdle(arg1:string,arg2:boolean):Promise<void>;

export function SftpCancelTransfer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpList(arg1:string,arg2:string):Promise<Array<models.SFTPEntry>>;

export function SftpMkdir(arg1:string,arg2:string):Promise<void>;

export function SftpRemove(arg1:string,arg2:string):Promise<void>;

export function SftpRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartSysInfoCollector(arg1:string):Promise<void>;

export function StartTunnel(arg1:models.ServerNode,arg2:string,arg3:string,arg4:number,arg5:string,arg6:number):Promise<models.TunnelInfo>;

export function StopSysInfoCollector(arg1:string):Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function SyncSftpToTerminal(arg1:string,arg2:string):Promise<void>;

export function TestServer(arg1:models.ServerNode):Promise<models.ServerTestResult>;

export function TestServers(arg1:Array<models.ServerNode>):Promise<Array<models.ServerTestResult>>;

export function UnlockWithMasterPassword(arg1:string):Promise<void>;

export function UpdateTunnel(arg1:string,arg2:models.ServerNode,arg3:string,arg4:string,arg5:number,arg6:string,arg7:number):Promise<models.TunnelInfo>;

export function Write(arg1:string,arg2:string):Promise<void>;

export function WriteLocalFileBase64(arg1:string,arg2:string):Promise<void>;
