// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddGroup(arg1:string):Promise<void>;

export function Connect(arg1:string,arg2:models.ServerNode,arg3:number,arg4:number):Promise<models.ConnectResult>;

export function DeleteCredential(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetCredentials():Promise<Array<models.Credential>>;

export function GetGroups():Promise<Array<string>>;

export function GetServers():Promise<Array<models.ServerNode>>;

export function GetSettings():Promise<models.Settings>;

export function ListSessions():Promise<Array<models.SessionInfo>>;

export function ListTunnels():Promise<Array<models.TunnelInfo>>;

export function RemoveGroup(arg1:string):Promise<void>;

export function RemoveTunnel(arg1:string):Promise<void>;

export function RenameGroup(arg1:string,arg2:string):Promise<void>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartTunnel(arg1:string):Promise<void>;

export function SaveCredential(arg1:models.Credential):Promise<models.Credential>;

export function SaveServer(arg1:models.ServerNode):Promise<models.ServerNode>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SelectImageFile():Promise<string>;

export function SelectKeyFile():Promise<string>;

export function SelectLocalFile():Promise<string>;

export function SelectSavePath(arg1:string):Promise<string>;

export function SftpCancelTransfer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpList(arg1:string,arg2:string):Promise<Array<models.SFTPEntry>>;

export function SftpUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartTunnel(arg1:models.ServerNode,arg2:string,arg3:number,arg4:string,arg5:number):Promise<models.TunnelInfo>;

export function StopTunnel(arg1:string):Promise<void>;

export function Write(arg1:string,arg2:string):Promise<void>;
