// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommandHistory(arg1, arg2) {
  return window['go']['main']['App']['AddCommandHistory'](arg1, arg2);
}

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function ChangeMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeMasterPassword'](arg1, arg2);
}

export function ClearCommandHistory(arg1) {
  return window['go']['main']['App']['ClearCommandHistory'](arg1);
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DisableMasterPassword(arg1) {
  return window['go']['main']['App']['DisableMasterPassword'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function EnableMasterPassword(arg1) {
  return window['go']['main']['App']['EnableMasterPassword'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GetCredentials() {
  return window['go']['main']['App']['GetCredentials']();
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetSecurityStatus() {
  return window['go']['main']['App']['GetSecurityStatus']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportConfig(arg1, arg2) {
  return window['go']['main']['App']['ImportConfig'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function QueryCommandHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryCommandHistory'](arg1, arg2, arg3);
}

export function ReadLocalFileBase64(arg1) {
  return window['go']['main']['App']['ReadLocalFileBase64'](arg1);
}

export function Reconnect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Reconnect'](arg1, arg2, arg3);
}

export function RemoveGroup(arg1) {
  return window['go']['main']['App']['RemoveGroup'](arg1);
}

export function RemoveTunnel(arg1) {
  return window['go']['main']['App']['RemoveTunnel'](arg1);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['main']['App']['Resize'](arg1, arg2, arg3);
}

export function RestartTunnel(arg1) {
  return window['go']['main']['App']['RestartTunnel'](arg1);
}

export function SaveCredential(arg1) {
  return window['go']['main']['App']['SaveCredential'](arg1);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SelectKeyFile() {
  return window['go']['main']['App']['SelectKeyFile']();
}

export function SelectLocalFile() {
  return window['go']['main']['App']['SelectLocalFile']();
}

export function SelectLocalFiles() {
  return window['go']['main']['App']['SelectLocalFiles']();
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}

export function SetSftpPathFromTerminal(arg1, arg2) {
  return window['go']['main']['App']['SetSftpPathFromTerminal'](arg1, arg2);
}

export function SetSysInfoIdle(arg1, arg2) {
  return window['go']['main']['App']['SetSysInfoIdle'](arg1, arg2);
}

export function SftpCancelTransfer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpCancelTransfer'](arg1, arg2, arg3);
}

export function SftpDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpDownload'](arg1, arg2, arg3);
}

export function SftpList(arg1, arg2) {
  return window['go']['main']['App']['SftpList'](arg1, arg2);
}

export function SftpMkdir(arg1, arg2) {
  return window['go']['main']['App']['SftpMkdir'](arg1, arg2);
}

export function SftpRemove(arg1, arg2) {
  return window['go']['main']['App']['SftpRemove'](arg1, arg2);
}

export function SftpRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRename'](arg1, arg2, arg3);
}

export function SftpUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpUpload'](arg1, arg2, arg3);
}

export function StartSysInfoCollector(arg1) {
  return window['go']['main']['App']['StartSysInfoCollector'](arg1);
}

export function StartTunnel(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StopSysInfoCollector(arg1) {
  return window['go']['main']['App']['StopSysInfoCollector'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function SyncSftpToTerminal(arg1, arg2) {
  return window['go']['main']['App']['SyncSftpToTerminal'](arg1, arg2);
}

export function UnlockWithMasterPassword(arg1) {
  return window['go']['main']['App']['UnlockWithMasterPassword'](arg1);
}

export function Write(arg1, arg2) {
  return window['go']['main']['App']['Write'](arg1, arg2);
}

export function WriteLocalFileBase64(arg1, arg2) {
  return window['go']['main']['App']['WriteLocalFileBase64'](arg1, arg2);
}
